dmci_pro/dmci_app/urls.py
from django.urls import path
from . import views

app_name = 'dmci_app'
urlpatterns = [
    path('', views.portal, name='portal'),
    path('main_form/', views.main_form, name='main_form'),
    path('compo_form/', views.compo_form, name='compo_form'),
    path('compo_list/', views.compo_list_data, name='compo_list_data'),
    path('confirm/', views.confirm_before_write_db, name='confirm_write_db'),
    path('list_all_data/', views.list_all_data, name='list_all_data'),
]

dmci_pro/dmci_pro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dmci_app.urls')),
]

dmci_pro/dmci_app/models.py
from django.db import models

# Create your models here.

class DjangoTestMain(models.Model):
    id = models.AutoField(primary_key=True)
    quatation_meta_id = models.CharField(max_length=100)
    quatation_subject = models.TextField(blank=True, null=True)
    customer_id = models.CharField(max_length=100, blank=True, null=True)
    reserve_num = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    quatation_total = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    created_datetime = models.DateTimeField(blank=True, null=True)
    updated_datetime = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'django_test_main'


class DjangoTestCompo(models.Model):
    id_num = models.AutoField(primary_key=True)
    quatation_meta_id = models.CharField(max_length=100)
    product_name = models.CharField(max_length=100, blank=True, null=True)
    product_text = models.TextField(blank=True, null=True)
    unit_price = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    total = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    created_datetime = models.DateTimeField(blank=True, null=True)
    updated_datetime = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'django_test_compo'

dmci_pro/dmci_app/forms.py
from django import forms
from django.forms import Form, ModelForm, IntegerField, CharField
from .models import DjangoTestCompo 
from .models import DjangoTestMain 


class CompoForm(forms.Form):

    products = (
            ("product_1", "product_1"),
            ("product_2", "product_2"),
            ("product_3", "product_3"),
    )

    product_name = forms.ChoiceField(label = "プロダクト名", choices = products)

    '''
    product_name = forms.CharField(
        label='プロダクト名',
        required=False,
        max_length=100,
    )
    '''

    product_text = forms.CharField(
        label='プロダクトテキスト',
        required=True,
        max_length=500,
        widget=forms.Textarea,
    )
    
    qty = forms.IntegerField(
            label='数量',
            initial=0,
            required=True,
    )

    unit_price = forms.IntegerField(
            label='単体価格',
            initial=0,
            required=True,
    )

class MainForm(forms.Form):
    quatation_meta_id = forms.CharField(
            label='見積もりID',
            required=True,
            max_length=100,
    )

    quatation_subject = forms.CharField(
            label = '見積もり名',
            #required = True,
            required = False,
            max_length = 100,
    )

    customer_id = forms.CharField(
            label = '顧客名',
            required = False,
            max_length = 100,
    )

class ConfirmForm(forms.Form):
    pass

dmci_pro/dmci_app/views.py
import datetime

from django.shortcuts import render, redirect
from .models import DjangoTestMain
from .models import DjangoTestCompo
from .forms import CompoForm, MainForm, ConfirmForm

# Create your views here.

# 見積もり管理番号
quatation_meta_id = ''

# 入力値オブジェクト用リスト
input_compo_object_list = []

# メイン入力値オブジェクト
class InputMainObject:
    def __init__(self):
        self.quatation_meta_id = ''
        self.quatation_subject = ''
        self.customer_id = ''
        self.quatation_total = 0

# 入力値オブジェクト
class InputCompoObject:
    def __init__(self):
        self.product_name = ''
        self.product_text = ''
        self.unit_price = 0
        self.qty = 0
        self.total = 0

# メイン入力オブジェクト
main_obj = InputMainObject()

# 構成入力フォームナンバー
compo_form_num = 0


# ポータル画面
def portal(request):
    return render(request, 'portal.html')


# 見積もりメイン入力画面
def main_form(request):
    # 入力値オブジェクト作成
    #main_obj = InputMainObject()

    form = MainForm
    context = {
            'form': form,
            }

    if request.method == 'POST':
        form = MainForm(request.POST)
        # プレビューページへ
        if form.is_valid() and ('button_1' in request.POST):
            context = {
                'form': form,
            }
            return render(request, 'main/main_preview.html', context = context)

        # オブジェクトに入力して構成入力に
        elif form.is_valid() and ('button_2' in request.POST):
            main_obj.quatation_meta_id = form.data['quatation_meta_id']
            main_obj.quatation_subject = form.data['quatation_subject']
            main_obj.customer_id = form.data['customer_id']

            return redirect('/compo_form/')

    return render(request, 'main/main_form.html', context)


# 構成入力画面
def compo_form(request):
    form = CompoForm
    global compo_form_num
    #global input_compo_object_list
    # 入力値オブジェクト作成
    compo_obj = InputCompoObject()
    # 入力値オブジェクトへインプット関数
    def input_compo_object(element_num, product_name, product_text, unit_price, qty, total):
        input_compo_object_list[element_num].product_name = product_name
        input_compo_object_list[element_num].product_text = product_text
        input_compo_object_list[element_num].unit_price = unit_price
        input_compo_object_list[element_num].qty = qty
        input_compo_object_list[element_num].total = total

    # 構成登録ページ
    if request.method == 'POST':
        form = CompoForm(request.POST)

        # プレビューページへ
        if form.is_valid() and ('button_1' in request.POST):
            # トータル金額計算
            unit_price = int(form.data['unit_price'])
            qty = int(form.data['qty'])
            total_price = unit_price * qty

            context = { 'form': form,
                        'total_price': total_price,
                        'compo_num': compo_form_num + 1,
                        }
            # オブジェクトリストへオブジェクト追加
            input_compo_object_list.append(compo_obj)

            #オブジェクトへ入力
            input_compo_object(compo_form_num, form.data['product_name'], form.data['product_text'], form.data['unit_price'], form.data['qty'], total_price)

            return render(request, 'compo/compo_preview.html', context = context)

        # もう一つ構成登録する
        elif form.is_valid() and ('button_2' in request.POST):
            compo_form_num += 1
            context = {
                    'form': form,
                    'compo_num': compo_form_num + 1
            }
            return render(request, 'compo/compo_form.html', context = context) 


        elif form.is_valid() and ('button_3' in request.POST):
            return redirect('/confirm/')

    context = {
            'form': form,
            'compo_num': compo_form_num + 1
            }

    return render(request, 'compo/compo_form.html', context)


def compo_list_data(request):
    data = DjangoTestCompo.objects.all()

    context = {
            'data': data,
            }
    return render(request, 'compo/compo_list.html', context)


# db書き込み前確認と書き込み
def confirm_before_write_db(request):
    global input_compo_object_list
    #form = ConfirmForm
    if request.method == 'POST':
        form = ConfirmForm(request.POST)
        if form.is_valid() and ('button_1' in request.POST):
            # DB書き込み時間取得
            created_datetime = datetime.datetime.now() + datetime.timedelta(hours=9)
            # 見積もりメインDB書き込み
            main_set = DjangoTestMain.objects.create(
                quatation_meta_id = main_obj.quatation_meta_id,
                quatation_subject = main_obj.quatation_subject,
                customer_id = main_obj.customer_id,
                quatation_total = main_obj.quatation_total,
                created_datetime = created_datetime,
            )

            # 構成DB書き込み
            for input_object in input_compo_object_list:
                compo_set = DjangoTestCompo.objects.create(
                    quatation_meta_id = main_obj.quatation_meta_id,
                    product_name = input_object.product_name,
                    product_text = input_object.product_text,
                    unit_price = input_object.unit_price,
                    qty = input_object.qty,
                    total = input_object.total,
                    created_datetime = created_datetime,
                )

            return redirect('/list_all_data/') 
                    
            # compo object list初期化
            input_compo_object_list = []
            compo_form_num = 0

    return render(request, 'confirm.html')


# すべてのデータ表示
def list_all_data(request):
    main_data = DjangoTestMain.objects.all()
    compo_data = DjangoTestCompo.objects.all()

    context = {
            'main_data': main_data,
            'compo_data': compo_data,
            }
    return render(request, 'list_all_data.html', context)

dmci_pro/dmci_app/templates/compo/compo_form.html
<form action="{% url 'dmci_app:compo_form' %}" method="POST">{% csrf_token %}

    <div>構成:{{ compo_num }}</div>
    <br>
    <div>プロダクト名:</div>
    <div>{{ form.product_name }}</div>
        {% if form.errors.title %}
            {% for error in form.errors.title %}
                <div><font color="red">{{ error }}</font></div>
            {% endfor %}
        {% endif %}
   <br>
    <div>プロダクトテキスト:</div>
    <div>{{ form.product_text }}</div>
        {% if form.errors.text %}
            {% for error in form.errors.text %}
                <div><font color="red">{{ error }}</font></div>
            {% endfor %}
        {% endif %}
   <br>
   <div>単体価格：</div>
   <div>{{ form.unit_price }}</div>
   <br>
   <div>数量：</div>
   <div>{{ form.qty }}</div>
   <br>
    <button type="submit" name="button_1">登録プレビューへ</button>
</form>

dmci_pro/dmci_app/templates/compo/compo_list.html
{% load tz %}
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Data</th>
            <th>created</th>
            <th>updated</th>
            <th>unit price</th>
            <th>qty</th>
            <th>total price</th>
        </tr>
    </thead>
    <tbody>
        {% for object in data %}
        <tr>
            <td>
                    {{ object.id_num }}
            </td>
            <td>
                    {{ object.product_name }}
            </td>
            <td>
                    {{ object.product_text }}
            </td>
            <td>
                    {{ object.created_datetime}}
                    {% get_current_timezone as TIME_ZONE %}
                    {{ TIME_ZONE }}
            </td>
            <td>
                    {{ object.updated_datetime }}
            </td>
            <td>
                    {{ object.unit_price }}
            </td>
            <td>
                    {{ object.qty }}
            </td>
            <td>
                    {{ object.total }}
            </td>
            <form method="POST">
                {% csrf_token %}
                <td><button type="submit" name={{ object.id_num }}>select</td>
            </form>
        </tr>
        {% endfor %}
    </tbody>
</table>
        <br>
    <p>
    <a href="http://10.0.1.5:8080/">TOP</a>

dmci_pro/dmci_app/templates/compo/compo_preview.html
<div>構成：{{ compo_num }} </div>
<br>
{% for field in form %}
    {{ field.name }}:{{ field.value }}<br>
{% endfor %}

<form method="POST" action="">
    {% csrf_token %}
    {% for field in form %}
       {{ field.as_hidden }}
    {% endfor %}
    トータル：￥{{ total_price }}
    <p>
    <input type="submit" name="button_3" value="構成登録終了してその他製品登録">
    <input type="submit" name="button_2" value="別の構成を追加登録">
    <input type="submit" name="button_4" value="内部バッファをすべてリセット">
    <button type="button" onclick="history.back()">戻る</button>
</form>

dmci_pro/dmci_app/templates/compo/compo_register.html
OK!

<p>
<a href='http://10.0.1.5:8080/myapp/'>ポータル</a>
<p>
<a href='http://10.0.1.5:8080/myapp/list/'>データリスト</a>